import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ThemeTogglebutton from "@/components/ui/ThemeToggle";
import ToasterwithTheme from "@/components/ui/ToasterwithTheme";

const font = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nextjs + Shadcn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider attribute="class">
          <ThemeTogglebutton className="absolute top-2 right-6" />
          {children}
          <ToasterwithTheme />
        </ThemeProvider>
      </body>
    </html>
  );
}
